Story - Inbox service 
As a helpdesk operator,
I want to have a system that receive any report generated by customers,
So that I save effort and time since less phone calls are received.

Scenario: Report creation
Given a customer has a problem,
When a phone call is received
And the voice recognition system understands to the customer,,
Then the system records the message
And a new issue report is created.

Scenario: Passing incoming call
Given a customer is calling,
When the voice recognition system does not understand to the customer,
Then the call is attended by a helpdesk operator.